### ISSUE TITLE
All devices getting logged as "Unknown Device"

### ISSUE THREAD

**Issue by rmevans9** [lwansbrough/react-native-google-analytics#23]
This is more of a question then a issue. I got everything logging correctly now with the exception that in realtime everything shows as "Desktop" and instead of getting information on devices using the app I see "Unrecognized Device". Is this what everyone is seeing currently? I have plan to resolve if it is but I just want to make sure I am not missing something simple first.

**Comment by MrJacobJunker** [comment]
I also get all realtime data as "Desktop". I've setup my GA project as a mobile app, and I don't get any data in the App Overview. I think this might be because of the "Desktop" registration, as there is a warning saying "This report has been filtered to include only data where there are values for "Mobile Device Branding" dimension." - though just a guess.

**Comment by rmevans9** [comment]
Yes, that is actually why I have https://github.com/lwansbrough/react-native-google-analytics/pull/24 open. I already got react-native-device-info to merge in getting the user agent so this PR would allow for you to get the data to show correctly in GA. You could npm install my repo directly until this PR is merged if you need it badly enough.

Closing as I have a PR to resolve this issue.
